---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: network-tools-with-jmeter build
  name: network-tools-with-jmeter-build

parameters:
- name: NAME
  value: network-tools-with-jmeter
- name: NETWORK_TOOLS_VERSION
  value: "4.8"
- name: GIT_REPO
  value: https://github.com/redhat-gpte/network-tools-with-jmeter.git
- name: GIT_REF
  value: main

objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/display-name: Network Tools
    name: network-tools-rhel8
    namespace: openshift
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        description: An image containing a set of tools and scripts to debug OpenShift Networking issues
        openshift.io/display-name: Network Tools
        version: ${NETWORK_TOOLS_VERSION}
      from:
        kind: DockerImage
        name: registry.redhat.io/openshift4/network-tools-rhel8:v${NETWORK_TOOLS_VERSION}
      generation: 2
      importPolicy:
        scheduled: true
      name: ${NETWORK_TOOLS_VERSION}
      referencePolicy:
        type: Local

- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: ${NAME}
  spec:
    lookupPolicy:
      local: false

- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: ${NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}:latest
    source:
      git:
        ref: ${GIT_REF}
        uri: ${GIT_REPO}
      type: Git
    strategy:
      type: Docker
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: network-tools-rhel8:${NETWORK_TOOLS_VERSION}
          namespace: openshift
...
