{{ if .Values.deploy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "network-tools-with-jmeter.name" . }}
  labels:
    {{- include "network-tools-with-jmeter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "network-tools-with-jmeter.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "network-tools-with-jmeter.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: shell
        image: {{ include "network-tools-with-jmeter.image" . | quote }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - name: smtp-tls
          mountPath: /smtp-tls
          readOnly: true
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end }}
